fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\Auth\User
    from_email:
        address: "hello@sender.com"
        sender_name: "Wonder postman"
    registration:
        form:
          type: App\Form\Auth\RegistrationFormType
        confirmation:
          enabled: true