# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']

    transport: smtp
    host:      smtp.gmail.com
    username:  my_username@gmail.com
    password:  my_password
    encryption: ssl
    spool:     { type: memory }
