<?php

namespace App\Repository\Learn;

use App\Entity\Learn\Category;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Category::class);
    }

    public function findAllWithFortuneCookiesLength()
    {
        $qb = $this->createQueryBuilder('category');

        $this->addFortuneCookieJoinAndSelect($qb);

        return $qb->getQuery()->getResult();
    }

    public function search($term)
    {
        $qb =  $this->createQueryBuilder('category')
            ->andWhere('category.name LIKE :searchTerm 
                OR category.iconKey LIKE :searchTerm
                OR fc.fortune LIKE :searchTerm
                ')
            ->setParameter('searchTerm', $term);

        $this->addFortuneCookieJoinAndSelect($qb);

        return $qb->getQuery()->getResult();
    }

    public function createAlphabeticalQueryBuilder()
    {
        return $this->createQueryBuilder('cat')
            ->orderBy('cat.name', 'ASC');
    }

    private function addFortuneCookieJoinAndSelect(QueryBuilder $qb){

        return $qb->leftJoin('category.fortuneCookies', 'fc')->addSelect('fc');
    }


}
